version: '3.7'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: TestTestTest
      POSTGRES_DB: test
    image: postgres:alpine
    networks:
      - default
    ports:
      - 5401:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  service:
    build:
      context: .
    depends_on:
      - db
    environment:
      - NODE_ENV=dev
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    restart: always
